apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-ord.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7050
      targetPort: 7050
      protocol: TCP
      name: grpc
  selector:
    app: {{ include "hlf-ord.name" . }}
    release: {{ .Release.Name }}
