apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hlf-couchdb.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "hlf-couchdb.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
{{ include "labels.standard" . | indent 8 }}
    spec:
      volumes:
      - name: data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.existingClaim | default (include "hlf-couchdb.fullname" .) }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "hyperledger/fabric-couchdb:0.4.10"
          imagePullPolicy: IfNotPresent
          envFrom:
          - secretRef:
              name: {{ include "hlf-couchdb.fullname" . }}
          volumeMounts:
          - mountPath: /opt/couchdb/data
            name: data
          ports:
            - name: couchdb
              containerPort: 5984
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 60
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            tcpSocket:
              port: 5984
            initialDelaySeconds: 5
            timeoutSeconds: 3
            periodSeconds: 5
