apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hlf-couchdb.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
type: Opaque
data:
  COUCHDB_USERNAME:  {{ .Values.couchdbUsername | b64enc | quote }}
  COUCHDB_PASSWORD: {{ randAlphaNum 24 | b64enc | quote }}
