apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-couchdb.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 5984
      targetPort: couchdb
      protocol: TCP
      name: couchdb
  selector:
    app: {{ include "hlf-couchdb.name" . }}
    release: {{ .Release.Name }}
