apiVersion: v1
kind: Service
metadata:
  name: {{ include "hlf-peer.fullname" . }}
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 7051
      targetPort: 7051
      protocol: TCP
      name: request
    - port: 7053
      targetPort: 7053
      protocol: TCP
      name: event
    - port: 9443
      targetPort: 9443
      protocol: TCP
      name: metrics
  selector:
    app: {{ include "hlf-peer.name" . }}
    release: {{ .Release.Name }}
